CREATE TABLE IF NOT EXISTS applications (
    id SERIAL PRIMARY KEY,
    vk VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    nick VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);